version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.0.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: